#pragma once
#include <stdint.h>
// Generated by tools/generate_recognition.py; edit recognition.json.
struct IoHomePresentation { uint8_t type; uint8_t flags; };
inline IoHomePresentation ioHomePresentation(uint16_t packed)
{
    switch(packed) {
    case 0x0040: return {1, 1};
    case 0x0080: return {1, 0};
    case 0x0081: return {1, 1};
    case 0x0082: return {1, 0};
    case 0x00C0: return {3, 0};
    case 0x0100: return {2, 0};
    case 0x0101: return {2, 0};
    case 0x0140: return {4, 0};
    case 0x017A: return {4, 2};
    case 0x0180: return {6, 4};
    case 0x01BA: return {6, 2};
    case 0x01C0: return {7, 0};
    case 0x01FA: return {7, 2};
    case 0x0240: return {8, 0};
    case 0x0241: return {8, 0};
    case 0x0280: return {1, 0};
    case 0x0340: return {1, 0};
    case 0x0380: return {5, 0};
    case 0x03C0: return {12, 0};
    case 0x0400: return {9, 0};
    case 0x0440: return {1, 1};
    case 0x0480: return {1, 1};
    case 0x04C0: return {10, 0};
    case 0x0500: return {11, 0};
    case 0x0501: return {11, 0};
    case 0x0502: return {11, 0};
    case 0x0503: return {11, 0};
    case 0x0540: return {13, 0};
    case 0x057A: return {14, 2};
    case 0x0600: return {1, 0};
    case 0x0601: return {1, 0};
    case 0x0740: return {1, 0};
    default: return {0,0};
    }
}
