#!/usr/bin/env python3
"""One checked manifest drives firmware presentation and old-firmware ETS fallback."""
import argparse,json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
rows=json.loads((root/'src/protocol/recognition.json').read_text())
assert len({r['packed'] for r in rows})==len(rows)
assert all(0<=r['packed']<=65535 and 1<=r['type']<=14 and 0<=r['flags']<=7 for r in rows)
cpp='#pragma once\n#include <stdint.h>\n// Generated by tools/generate_recognition.py; edit recognition.json.\nstruct IoHomePresentation { uint8_t type; uint8_t flags; };\ninline IoHomePresentation ioHomePresentation(uint16_t packed)\n{\n    switch(packed) {\n'
cpp+=''.join(f"    case 0x{r['packed']:04X}: return {{{r['type']}, {r['flags']}}};\n" for r in rows)
cpp+='    default: return {0,0};\n    }\n}\n'
js='// BEGIN GENERATED RECOGNITION\nvar IOHC_PRESENTATIONS = {\n'+',\n'.join(f"    {r['packed']}: [{r['type']}, {r['flags']}]" for r in rows)+'\n};\n'
js+='''function IOHC_etsDeviceType(p,s) { return (IOHC_PRESENTATIONS[(p<<6)|s] || [0,0])[0]; }
function IOHC_hasOrientationObjects(p,s) { return (IOHC_PRESENTATIONS[(p<<6)|s] || [0,0])[1]&1; }
function IOHC_isBinaryOnly(p,s) { return ((IOHC_PRESENTATIONS[(p<<6)|s] || [0,0])[1]>>1)&1; }
// END GENERATED RECOGNITION
'''
p=root/'src/IoHomecontrol.script.js';source=p.read_text()
start=source.find('// BEGIN GENERATED RECOGNITION')
if start<0:start=source.index('function IOHC_etsDeviceType(')
end=source.index('function IOHC_importDeviceLabel(',start)
updated=source[:start]+js+'\n'+source[end:]
check=argparse.ArgumentParser();check.add_argument('--check',action='store_true');args=check.parse_args()
for path,text in [(root/'src/protocol/IoHomePresentation.h',cpp),(p,updated)]:
 if args.check: assert path.read_text()==text,f'stale generated file: {path}'
 else:path.write_text(text)
