#!/usr/bin/env python3
"""Generate scoped diagnostic catalogue, never automatic discovery permissions."""
import argparse,json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
rows=json.loads((root/'src/protocol/semantics.json').read_text())
assert len({(r['product'],r['index'],r['meaning']) for r in rows})==len(rows)
assert all(0<=r['index']<=16 and r['source'] and not r['rfWrite'] and not r['knxPublish'] and not r['automaticBinding'] for r in rows)
quote=lambda value:json.dumps(value,ensure_ascii=True)
cpp='#pragma once\n#include <stdint.h>\n// Generated by tools/generate_semantics.py; product-scoped diagnostics only.\nstruct IoHomeSemantic {const char *product;uint8_t index;const char *meaning,*unit,*conversion,*specials,*source;bool rfWrite,knxPublish,automaticBinding;};\nstatic constexpr IoHomeSemantic kIoHomeSemantics[]={\n'
for r in rows:cpp+=' {'+','.join([quote(r['product']),str(r['index'])]+[quote(r[k]) for k in ('meaning','unit','conversion','specials','source')]+['false','false','false'])+'},\n'
cpp+='};\n'
js='// BEGIN GENERATED SEMANTICS\nvar IOHC_SEMANTICS='+json.dumps(rows,ensure_ascii=True,separators=(',',':'))+';\n// END GENERATED SEMANTICS\n'
p=root/'src/IoHomecontrol.script.js';s=p.read_text();start=s.find('// BEGIN GENERATED SEMANTICS')
if start<0:updated=s+'\n'+js
else:end=s.index('// END GENERATED SEMANTICS',start)+len('// END GENERATED SEMANTICS\n');updated=s[:start]+js+s[end:]
a=argparse.ArgumentParser();a.add_argument('--check',action='store_true');args=a.parse_args()
for p,text in [(root/'src/protocol/IoHomeSemanticCatalogue.h',cpp),(p,updated)]:
 if args.check:assert p.read_text()==text,f'stale generated file: {p}'
 else:p.write_text(text)
